apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-db
  template:
    metadata:
      labels:
        app: cqrs-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cqrs-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cqrs-db
  ports:
    - port: 5432
      targetPort: 5432
