apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: cqrs-worker
  template:
    metadata:
      labels:
        app: cqrs-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "consumers.py"]
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@cqrs-db:5432/{{ .Values.postgres.db }}"
            - name: REDIS_URL
              value: "redis://cqrs-redis:6379"
