apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-api
  namespace: cqrs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cqrs-api
  template:
    metadata:
      labels:
        app: cqrs-api
    spec:
      containers:
        - name: api
          image: tu-registry/cqrs-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@cqrs-db:5432/cqrs_db
            - name: REDIS_URL
              value: redis://cqrs-redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: cqrs-api
  namespace: cqrs-demo
spec:
  selector:
    app: cqrs-api
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
