apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-redis
  namespace: cqrs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-redis
  template:
    metadata:
      labels:
        app: cqrs-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cqrs-redis
  namespace: cqrs-demo
spec:
  selector:
    app: cqrs-redis
  ports:
    - port: 6379
      targetPort: 6379
