version: '3.8'
services:
db:
image: postgres:15
restart: always
environment:
POSTGRES_USER: products_user
POSTGRES_PASSWORD: products_pass
POSTGRES_DB: products
ports:
- "5432:5432"
volumes:
- postgres_data:/var/lib/postgresql/data


app:
build: .
ports:
- "8000:80"
env_file:
- .env
depends_on:
- db


volumes:
postgres_data: